server:
  port: 8080

database:
  host: localhost
  port: 3306
  user: root
  password: password
  dbname: coffee_shop

redis:
  host: localhost
  port: 6379
  password: ""

kafka:
  brokers:
    - "localhost:9092"
  topics:
    orders: "orders"
    inventory: "inventory"
    payments: "payments"
    emailConfirmation: "email_confirmation"
  consumerGroup: "coffee-shop-consumer"
  bootstrap_servers: "localhost:9092"

email:
  smtpHost: "localhost"
  smtpPort: "1025"
  senderEmail: "youremail@gmail.com"
  senderPasswd: "your-email-password"

jwt:
  secret_key: "your_secret_key_here"